### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by mcarifio** [RedSnake64/openwrt-yun#3]
I'd like to install the 1.3 release. Even just a checklist of commands to issue would help. Thanks.

**Comment by RedSnake64** [comment]
Hi mcarifio,

you can easily flash the new system with the openwrt webpanel.
Just download the `openwrt-1.3-ar71xx-generic-yun-squashfs-sysupgrade.bin`and flash it, but make sure you untick the "Keep Settings" checkbox before.

(https://clockworkbird9.wordpress.com/2016/01/23/new-openwrt-series-1-setting-up-openwrt-chaos-calmer-for-arduino-yun/)
