### ISSUE TITLE
USB sound card issue

### ISSUE THREAD

**Issue by sai-y** [RedSnake64/openwrt-yun#4]
I am experiencing a weird problem with my USB sound card (The Yun runs Chaos Calmer). Every now and then, the sound card stops working. I took a look at the system messages when it stops working. I see these messages:

`
[ 3152.500000] retire_capture_urb: 5000 callbacks suppressed
[ 3157.510000] retire_capture_urb: 5000 callbacks suppressed
[ 3162.520000] retire_capture_urb: 5000 callbacks suppressed
[ 3167.530000] retire_capture_urb: 5000 callbacks suppressed`

The sound card starts working only after power cycling/rebooting the Yun. This is also seen with the official Yun image from the arduino repo. This seems like a USB driver issue. Any thoughts on how to resolve this?

**Comment by RedSnake64** [comment]
Hi sai-y,

Please tell me more details...
Which USB sound card do you use?
Sound card directly connected to Yun? (without USB hub?)
Which driver?
How long does it work?
I will try a USB sound card next days.

**Comment by sai-y** [comment]
Hi,
1. I am using this sound card: http://www.bhphotovideo.com/bnh/controller/home?O=&sku=1123982&gclid=CIz3h-Pq68sCFYiVfgod-hACQw&Q=&ap=y&m=Y&c3api=1876%2C92051677562%2C&is=REG&A=details
2. Yes the sound card is interfaced directly to the Yun without a hub. 

3) It works with the kmod-usb-audio driver available with the Yun.

4) Sometimes it works for a day. Sometimes, it resets within a couple of hours. 

I used another sound card. It works without a problem on occasion. But then, on other occasions, the results were the same.

**Comment by sai-y** [comment]
Another update: It looks there used to be a similar problem with the
Raspberry Pi in the past.

https://github.com/raspberrypi/firmware/issues/197

I tried 22.05 kHz and it still failed. So, I am currently trying 16 kHz. It
looks like the USB audio driver might need a fix. I will keep you posted if
I learn anything.

**Comment by RedSnake64** [comment]
Hi sai-y,

Does it work with 16kHz?

**Comment by sai-y** [comment]
No. The problem repeats on 16 kHz as well. This is not a driver issue.

I spoke to the manufacturers of the Yun. This happens only with the V4 of
the Yuns and not V5. It turns out the V4 does not have a voltage regulator
that stabilizes the power supply. This is a hardware bug.

Sai

**Comment by RedSnake64** [comment]
Hi Sai,

Do you already tried a USB hub with an external power supply?

**Comment by sai-y** [comment]
Unfortunately, I cannot use a USB hub. My Yun is installed in the ceiling.

Sai
