### ISSUE TITLE
Broken HTTPS (ERR_CERT_AUTHORITY_INVALID)

### ISSUE THREAD

**Issue by sscirrus** [RedSnake64/openwrt-yun#9]
I have a Yun running your latest release, Chaos Calmer.

When I try to access arduino.local, it fails saying the page is not secure. Chrome says: 

`NET::ERR_CERT_AUTHORITY_INVALID`

When I click 'Advanced' then 'Proceed to 192.168.0.17 (unsafe)', it takes me to the page.
Clicking 'Details', Chrome explains: 'This certificate has not been verified by a third party'. The Country says 'ZZ', and the State/Province says 'Somewhere'.

I'm pretty sure this is why arduino.local isn't working. How can I/we fix this?

**Comment by RedSnake64** [comment]
Hi sscirrus,

this firmware use a self signed certificate and forwards to a secure connection automatically.
This behavior can be changed in '/etc/config/uhttpd'
Set 'option redirect_https' to 0

**Comment by sscirrus** [comment]
That fixes the browser warning error (with a device restart). Thank you!
